import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("/docs", "routes/docs.tsx"),
  route("/d/:docId", "routes/d.$docId.tsx"),
  route("/d/:docId/:tabSlug", "routes/d.$docId.$tabSlug.tsx"),
  route("/d/:docId/edit", "routes/d.$docId.edit.tsx"),
  route("/raw/:docId/:tabSlug", "routes/raw.$docId.$tabSlug.tsx"),
  route("/download/:docId/:tabSlug", "routes/download.$docId.$tabSlug.tsx"),
  route("/auth/magic", "routes/auth.magic.tsx"),
  route("/auth/callback", "routes/auth.callback.tsx"),
  route("/auth/claim", "routes/auth.claim.tsx"),
  route("/auth/logout", "routes/auth.logout.tsx"),
  route("/desktop/auth", "routes/desktop.auth.tsx"),
  route("/desktop/auth/callback", "routes/desktop.auth.callback.tsx"),
  route("/desktop/auth/exchange", "routes/desktop.auth.exchange.ts"),
  route("/desktop/session", "routes/desktop.session.ts"),
  route("/desktop/auth/revoke", "routes/desktop.auth.revoke.ts"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/dashboard/agents", "routes/dashboard.agents.tsx"),
  route("/dashboard/docs/:id/delete", "routes/dashboard.docs.$id.delete.tsx"),
  route("/dashboard/docs/:id/rename", "routes/dashboard.docs.$id.rename.tsx"),
  route("/healthz", "routes/healthz.tsx"),
  route("/mcp", "routes/mcp.ts"),
  route("/.well-known/oauth-protected-resource", "routes/well-known.oauth-protected-resource.ts"),
  route("/.well-known/oauth-protected-resource/mcp", "routes/well-known.oauth-protected-resource.mcp.ts"),
  route("/.well-known/oauth-authorization-server", "routes/well-known.oauth-authorization-server.ts"),
  route("/.well-known/openid-configuration", "routes/well-known.openid-configuration.ts"),
  route("/oauth/register", "routes/oauth.register.ts"),
  route("/oauth/authorize", "routes/oauth.authorize.tsx"),
  route("/oauth/token", "routes/oauth.token.ts"),
  route("/oauth/revoke", "routes/oauth.revoke.ts"),
  route("/sync/pull", "routes/sync.pull.ts"),
  route("/sync/push", "routes/sync.push.ts"),
  route("/__desktop/shutdown", "routes/desktop.shutdown.ts"),
  route("/desktop/conflicts", "routes/desktop.conflicts.tsx"),
  route("/__desktop/sync", "routes/desktop.sync.ts"),
] satisfies RouteConfig;
