/**
 * Copies the installed monaco-editor AMD assets into public/monaco so the
 * editor is served from our own origin instead of cdn.jsdelivr.net.
 *
 * Why: the AMD loader was fetching ~1 MB across 14 cross-origin requests before
 * the editor became usable, which put a third-party DNS + TLS handshake on the
 * critical path of opening a document (and made the editor unavailable whenever
 * that CDN was slow or blocked). Self-hosting keeps the exact same AMD
 * behaviour — including the language workers — but same-origin and cacheable.
 *
 * The output is a build artifact: it is gitignored and regenerated by the
 * `predev` / `prebuild` npm scripts.
 */
import { cp, rm, mkdir, readdir, stat } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const source = join(dirname(require.resolve("monaco-editor/package.json")), "min", "vs");
const destination = join(repoRoot, "public", "monaco", "vs");

async function dirSize(path) {
  let total = 0;
  for (const entry of await readdir(path, { withFileTypes: true })) {
    const child = join(path, entry.name);
    total += entry.isDirectory() ? await dirSize(child) : (await stat(child)).size;
  }
  return total;
}

await rm(join(repoRoot, "public", "monaco"), { recursive: true, force: true });
await mkdir(destination, { recursive: true });
await cp(source, destination, { recursive: true });

const version = require("monaco-editor/package.json").version;
const bytes = await dirSize(destination);
console.log(
  `[monaco] self-hosted v${version} → public/monaco/vs (${(bytes / 1048576).toFixed(1)} MB on disk, served from /monaco/vs)`
);
